# Generated by Django 6.0.3 on 2026-03-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('set_name', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('mythic', 'Mythic Rare')], max_length=20)),
                ('condition', models.CharField(choices=[('nm', 'Near Mint'), ('lp', 'Lightly Played'), ('mp', 'Moderately Played'), ('hp', 'Heavily Played')], max_length=20)),
                ('mana_cost', models.CharField(blank=True, max_length=50)),
                ('color_identity', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stock_quantity', models.PositiveIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
